project_name: pytest-rng
pkg_name: pytest_rng
repo_name: nengo/pytest-rng
description: Fixtures for seeding tests and making randomness reproducible

copyright_start: 2019
license: mit
main_branch: main

license_rst: {}

contributing_rst: {}

contributors_rst: {}

manifest_in: {}

setup_py:
  python_requires: ">=3.5"
  install_req:
    - numpy
    - pytest
  docs_req:
    - nbsphinx>=0.6.0
    - nengo_sphinx_theme>1.2.2
    - numpydoc>=0.9.2
    - sphinx
  entry_points:
    pytest11:
      - "rng = pytest_rng.plugin"
  classifiers:
    - "Development Status :: 5 - Production/Stable"
    - "Framework :: Pytest"
    - "Programming Language :: Python :: 3 :: Only"
    - "Programming Language :: Python :: 3.5"
    - "Programming Language :: Python :: 3.6"
    - "Programming Language :: Python :: 3.7"

setup_cfg:
  pytest:
    addopts:
      - "--cov"
      - "--cov-append"
    filterwarnings:
      - ignore:testdir.copy_example is an experimental api
    rng_salt: v1.0.0
    pytester_example_dir: pytest_rng/tests
    python_files: test_pytest.py
  pylint:
    disable:
      - missing-docstring
  coverage:
    omit_files:
      - "*/setup.py"

docs_conf_py:
  nengo_logo: general-small-light.svg
  one_page: True

ci_scripts:
  - template: static
  - template: test
    coverage: true
  - template: docs
  - template: deploy
    wheel: true

pre_commit_config_yaml: {}

pyproject_toml: {}
